apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  replicas: 1
  selector:
  # Matching our pods name to the metadata below
    matchLabels:
      app: moderation
  template:
    metadata: 
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: edwinnaranjo/moderation
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec:
  selector:
    app: moderation
  type: ClusterIP # Default is ClusterIP service
  ports:
    - name: moderation
      protocol: TCP
      port: 4003
      targetPort: 4003